In [1]:
import pandas as pd
import numpy as np

In [3]:
# map, applymap, getdummies

df=pd.DataFrame({'Name':['Sourav','Priyanshu','Simran','Anshu','Ansh','Anurag','Priyanka'],'class':['btech','bca','mca','btech','mcom','mba','mca'],'Rollno':[34,23,11,10,11,67,89]})
df

        Name  class  Rollno
0     Sourav  btech      34
1  Priyanshu    bca      23
2     Simran    mca      11
3      Anshu  btech      10
4       Ansh   mcom      11
5     Anurag    mba      67
6   Priyanka    mca      89

In [ ]:
df.loc[:,'class'].str.capitalize()

0    Btech
1      Bca
2      Mca
3    Btech
4     Mcom
5      Mba
6      Mca
Name: class, dtype: object

In [7]:
df.loc[:,'Rollno']= df.loc[:,'Rollno']+2

In [8]:
df

        Name  class  Rollno
0     Sourav  btech      36
1  Priyanshu    bca      25
2     Simran    mca      13
3      Anshu  btech      12
4       Ansh   mcom      13
5     Anurag    mba      69
6   Priyanka    mca      91

In [10]:
def funcCap(text):
    return text.capitalize()

In [ ]:
df.loc[:,'class']= df.loc[:,'class'].apply(funcCap)  # series

In [14]:
df

        Name  class  Rollno
0     Sourav  Btech      36
1  Priyanshu    Bca      25
2     Simran    Mca      13
3      Anshu  Btech      12
4       Ansh   Mcom      13
5     Anurag    Mba      69
6   Priyanka    Mca      91

In [17]:
df.map(lambda x: str(x)+' hi')

           Name     class Rollno
0     Sourav hi  Btech hi  36 hi
1  Priyanshu hi    Bca hi  25 hi
2     Simran hi    Mca hi  13 hi
3      Anshu hi  Btech hi  12 hi
4       Ansh hi   Mcom hi  13 hi
5     Anurag hi    Mba hi  69 hi
6   Priyanka hi    Mca hi  91 hi

In [19]:
df.applymap(lambda x: str(x)+' hi')

C:\Users\hp\AppData\Local\Temp\ipykernel_2740\2208046189.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: str(x)+' hi')

           Name     class Rollno
0     Sourav hi  Btech hi  36 hi
1  Priyanshu hi    Bca hi  25 hi
2     Simran hi    Mca hi  13 hi
3      Anshu hi  Btech hi  12 hi
4       Ansh hi   Mcom hi  13 hi
5     Anurag hi    Mba hi  69 hi
6   Priyanka hi    Mca hi  91 hi

In [38]:
titanic= pd.read_csv('Titanic-Dataset.csv')

In [39]:
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [40]:
titanic.Survived.value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [41]:
titanic.Survived= titanic.Survived.map({0:'Not Survived',1:'Survived'})

In [42]:
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,Not Survived,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,Survived,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,Survived,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,Survived,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,Not Survived,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,Not Survived,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,Survived,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,Not Survived,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,Survived,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,Not Survived,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [43]:
pd.get_dummies(titanic.Pclass, dtype='int')

     1  2  3
0    0  0  1
1    1  0  0
2    0  0  1
3    1  0  0
4    0  0  1
..  .. .. ..
886  0  1  0
887  1  0  0
888  0  0  1
889  1  0  0
890  0  0  1

[891 rows x 3 columns]

In [44]:
titanic.loc[:,[1,2,3]]=pd.get_dummies(titanic.Pclass, dtype='int')

In [45]:
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,1,2,3
0,1,Not Survived,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,0,1
1,2,Survived,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1,0,0
2,3,Survived,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,0,1
3,4,Survived,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1,0,0
4,5,Not Survived,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,Not Survived,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0,1,0
887,888,Survived,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,1,0,0
888,889,Not Survived,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,0,0,1
889,890,Survived,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,1,0,0
890,891,Not Survived,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,0,0,1

In [47]:
titanic.rename(columns={1:'Pclass1',2:'Pclass2',3:'Pclass3'},inplace=True)

In [48]:
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Pclass1,Pclass2,Pclass3
0,1,Not Survived,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,0,1
1,2,Survived,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1,0,0
2,3,Survived,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,0,1
3,4,Survived,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1,0,0
4,5,Not Survived,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,Not Survived,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0,1,0
887,888,Survived,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,1,0,0
888,889,Not Survived,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,0,0,1
889,890,Survived,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,1,0,0
890,891,Not Survived,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,0,0,1