In [1]:
import pandas as pd

In [2]:
df= pd.DataFrame([12,34,55,11,10])
df

    0
0  12
1  34
2  55
3  11
4  10

In [4]:
df= pd.DataFrame([[1,9,7,4],[5,6,7,8],[7,5,4,3]])
df

   0  1  2  3
0  1  9  7  4
1  5  6  7  8
2  7  5  4  3

In [18]:
df= pd.DataFrame([[1,9,7,4],[5,6,7,8],[7,5,4,3]], columns=['a','b','c','d'], index=['i','j','k'])
df

   a  b  c  d
i  1  9  7  4
j  5  6  7  8
k  7  5  4  3

In [ ]:
df1=pd.DataFrame({'Name':['Sourav','Priyanshu','Simran','Anshu','Arsh','Anurag','Priyanka'],'class':['btech','bca','mca','btech','mcom','mba','bca'],'Rollno':[34,32,11,10,45,67,89],''})
df1

        Name  class  Rollno
0     Sourav  btech      34
1  Priyanshu    bca      32
2     Simran    mca      11
3      Anshu  btech      10
4       Arsh   mcom      45
5     Anurag    mba      67
6   Priyanka    bca      89

In [19]:
# functions 
df1.head() # first five rows- by default 5

        Name  class  Rollno
0     Sourav  btech      34
1  Priyanshu    bca      32
2     Simran    mca      11
3      Anshu  btech      10
4       Arsh   mcom      45

In [26]:
df1.head(4)

        Name  class  Rollno
0     Sourav  btech      34
1  Priyanshu    bca      32
2     Simran    mca      11
3      Anshu  btech      10

In [27]:
df1.tail() # by default last 5

       Name  class  Rollno
2    Simran    mca      11
3     Anshu  btech      10
4      Arsh   mcom      45
5    Anurag    mba      67
6  Priyanka    bca      89

In [29]:
df1.tail(2)

       Name class  Rollno
5    Anurag   mba      67
6  Priyanka   bca      89

In [49]:
# access - [], . , loc, iloc 
df1['Name']

0       Sourav
1    Priyanshu
2       Simran
3        Anshu
4         Arsh
5       Anurag
6     Priyanka
Name: Name, dtype: object

In [50]:
df1.Name

0       Sourav
1    Priyanshu
2       Simran
3        Anshu
4         Arsh
5       Anurag
6     Priyanka
Name: Name, dtype: object

In [51]:
df1[:3]

        Name  class  Rollno
0     Sourav  btech      34
1  Priyanshu    bca      32
2     Simran    mca      11

In [52]:
df1['Name'][1:4]

1    Priyanshu
2       Simran
3        Anshu
Name: Name, dtype: object

In [53]:
df1.Name[:5]

0       Sourav
1    Priyanshu
2       Simran
3        Anshu
4         Arsh
Name: Name, dtype: object

In [54]:
df1[['Name','class','Rollno']]

        Name  class  Rollno
0     Sourav  btech      34
1  Priyanshu    bca      32
2     Simran    mca      11
3      Anshu  btech      10
4       Arsh   mcom      45
5     Anurag    mba      67
6   Priyanka    bca      89

In [55]:
df1.Rollno

0    34
1    32
2    11
3    10
4    45
5    67
6    89
Name: Rollno, dtype: int64

In [56]:
# loc, iloc 
df1.loc[:,:]  # rows, columns

        Name  class  Rollno
0     Sourav  btech      34
1  Priyanshu    bca      32
2     Simran    mca      11
3      Anshu  btech      10
4       Arsh   mcom      45
5     Anurag    mba      67
6   Priyanka    bca      89

In [57]:
df1.loc[:4,:]

        Name  class  Rollno
0     Sourav  btech      34
1  Priyanshu    bca      32
2     Simran    mca      11
3      Anshu  btech      10
4       Arsh   mcom      45

In [60]:
df1.iloc[:4,:]

        Name  class  Rollno
0     Sourav  btech      34
1  Priyanshu    bca      32
2     Simran    mca      11
3      Anshu  btech      10

In [62]:
df1.loc[:4,'Name']

0       Sourav
1    Priyanshu
2       Simran
3        Anshu
4         Arsh
Name: Name, dtype: object

In [63]:
df1.loc[:4,['class','Name']]

   class       Name
0  btech     Sourav
1    bca  Priyanshu
2    mca     Simran
3  btech      Anshu
4   mcom       Arsh

In [70]:
df1.iloc[:,2]

0    34
1    32
2    11
3    10
4    45
5    67
6    89
Name: Rollno, dtype: int64

In [71]:
df1.shape

(7, 3)

In [73]:
# add column 
df1.loc[:,'Total Marks']=50
df1

        Name  class  Rollno  Total Marks
0     Sourav  btech      34           50
1  Priyanshu    bca      32           50
2     Simran    mca      11           50
3      Anshu  btech      10           50
4       Arsh   mcom      45           50
5     Anurag    mba      67           50
6   Priyanka    bca      89           50

In [78]:
# add column 
df1.loc[:,'Marks']=[44,40,42,46,49,48,41]

In [77]:
df1

        Name  class  Rollno  Total Marks  Marks
0     Sourav  btech      34           50     44
1  Priyanshu    bca      32           50     40
2     Simran    mca      11           50     42
3      Anshu  btech      10           50     46
4       Arsh   mcom      45           50     49
5     Anurag    mba      67           50     48
6   Priyanka    bca      89           50     41

In [79]:
df1.loc[4,'Marks']=48

In [80]:
df1

        Name  class  Rollno  Total Marks  Marks
0     Sourav  btech      34           50     44
1  Priyanshu    bca      32           50     40
2     Simran    mca      11           50     42
3      Anshu  btech      10           50     46
4       Arsh   mcom      45           50     48
5     Anurag    mba      67           50     48
6   Priyanka    bca      89           50     41

In [81]:
df1.loc[:,'Total Marks']=70

In [82]:
df1

        Name  class  Rollno  Total Marks  Marks
0     Sourav  btech      34           70     44
1  Priyanshu    bca      32           70     40
2     Simran    mca      11           70     42
3      Anshu  btech      10           70     46
4       Arsh   mcom      45           70     48
5     Anurag    mba      67           70     48
6   Priyanka    bca      89           70     41

In [83]:
df1.loc[7,:]=['Jatin','btech',44,70,46]

In [84]:
df1

        Name  class  Rollno  Total Marks  Marks
0     Sourav  btech    34.0         70.0   44.0
1  Priyanshu    bca    32.0         70.0   40.0
2     Simran    mca    11.0         70.0   42.0
3      Anshu  btech    10.0         70.0   46.0
4       Arsh   mcom    45.0         70.0   48.0
5     Anurag    mba    67.0         70.0   48.0
6   Priyanka    bca    89.0         70.0   41.0
7      Jatin  btech    44.0         70.0   46.0

In [85]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         8 non-null      object
 1   class        8 non-null      object
 2   Rollno       8 non-null      float64
 3   Total Marks  8 non-null      float64
 4   Marks        8 non-null      float64
dtypes: float64(3), object(2)
memory usage: 452.0+ bytes

In [ ]:
df1.insert(3,column='New',value=1)

In [87]:
df1

        Name  class  Rollno  New  Total Marks  Marks
0     Sourav  btech    34.0    1         70.0   44.0
1  Priyanshu    bca    32.0    1         70.0   40.0
2     Simran    mca    11.0    1         70.0   42.0
3      Anshu  btech    10.0    1         70.0   46.0
4       Arsh   mcom    45.0    1         70.0   48.0
5     Anurag    mba    67.0    1         70.0   48.0
6   Priyanka    bca    89.0    1         70.0   41.0
7      Jatin  btech    44.0    1         70.0   46.0