In [1]:
import pandas as pd

In [2]:
df=pd.DataFrame({'Name':['Sourav','Priyanshu','Simran','Anshu','Arsh','Anurag','Priyanka'],'class':['btech','bca','mca','btech','mcom','mba','bca'],'Rollno':[34,32,11,10,45,67,89]})
df

        Name  class  Rollno
0     Sourav  btech      34
1  Priyanshu    bca      32
2     Simran    mca      11
3      Anshu  btech      10
4       Arsh   mcom      45
5     Anurag    mba      67
6   Priyanka    bca      89

In [3]:
df.insert(2, column='marks', value=[34,33,32,28,43,44,35])
df

        Name  class  marks  Rollno
0     Sourav  btech     34      34
1  Priyanshu    bca     33      32
2     Simran    mca     32      11
3      Anshu  btech     28      10
4       Arsh   mcom     43      45
5     Anurag    mba     44      67
6   Priyanka    bca     35      89

In [4]:
df.columns

Index(['Name', 'class', 'marks', 'Rollno'], dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      object
 1   class   7 non-null      object
 2   marks   7 non-null      int64
 3   Rollno  7 non-null      int64
dtypes: int64(2), object(2)
memory usage: 356.0+ bytes

In [6]:
# iterrows 

for i in df.iterrows():
    print(i)

(0, Name      Sourav
class      btech
marks         34
Rollno        34
Name: 0, dtype: object)
(1, Name      Priyanshu
class           bca
marks            33
Rollno           32
Name: 1, dtype: object)
(2, Name      Simran
class        mca
marks         32
Rollno        11
Name: 2, dtype: object)
(3, Name      Anshu
class     btech
marks        28
Rollno       10
Name: 3, dtype: object)
(4, Name      Arsh
class     mcom
marks       43
Rollno      45
Name: 4, dtype: object)
(5, Name      Anurag
class        mba
marks         44
Rollno        67
Name: 5, dtype: object)
(6, Name      Priyanka
class          bca
marks           35
Rollno          89
Name: 6, dtype: object)

In [7]:
df1=pd.DataFrame({'a':[1,2,3,4],'b':[4,3,2,1],'c':[3,7,8,5]})
df1

   a  b  c
0  1  4  3
1  2  3  7
2  3  2  8
3  4  1  5

In [8]:
df2=pd.DataFrame({'a':[11,2,3,4],'b':[4,3,24,1],'c':[3,7,80,5]})
df2

    a   b   c
0  11   4   3
1   2   3   7
2   3  24  80
3   4   1   5

In [9]:
pd.concat((df1,df2))

    a   b   c
0   1   4   3
1   2   3   7
2   3   2   8
3   4   1   5
0  11   4   3
1   2   3   7
2   3  24  80
3   4   1   5

In [18]:
df3=pd.DataFrame({'a':[11,2,3,4],'b':[4,3,24,1],'c':[3,7,80,5]})
df4=pd.DataFrame({'a':[1,2,3,4],'b':[4,3,2,1],'e':[3,7,8,5]})
print(df3)
print(df4)

    a   b   c
0  11   4   3
1   2   3   7
2   3  24  80
3   4   1   5
   a  b  e
0  1  4  3
1  2  3  7
2  3  2  8
3  4  1  5

In [14]:
pd.concat((df3,df4), ignore_index=True)

    a   b     c    e
0  11   4   3.0  NaN
1   2   3   7.0  NaN
2   3  24  80.0  NaN
3   4   1   5.0  NaN
4   1   4   NaN  3.0
5   2   3   NaN  7.0
6   3   2   NaN  8.0
7   4   1   NaN  5.0

In [ ]:
pd.concat((df3,df4), axis=1)   # axis=1 - column, axis=0 -rows

    a   b   c  a  b  e
0  11   4   3  1  4  3
1   2   3   7  2  3  7
2   3  24  80  3  2  8
3   4   1   5  4  1  5

In [19]:
df

        Name  class  marks  Rollno
0     Sourav  btech     34      34
1  Priyanshu    bca     33      32
2     Simran    mca     32      11
3      Anshu  btech     28      10
4       Arsh   mcom     43      45
5     Anurag    mba     44      67
6   Priyanka    bca     35      89

In [21]:
df.sort_values(by='marks',ascending=False)

        Name  class  marks  Rollno
5     Anurag    mba     44      67
4       Arsh   mcom     43      45
6   Priyanka    bca     35      89
0     Sourav  btech     34      34
1  Priyanshu    bca     33      32
2     Simran    mca     32      11
3      Anshu  btech     28      10

In [23]:
df.sort_values(by='marks',ascending=False,ignore_index=True,inplace=True)

In [ ]:
df

        Name  class  marks  Rollno
0     Anurag    mba     44      67
1       Arsh   mcom     43      45
2   Priyanka    bca     35      89
3     Sourav  btech     34      34
4  Priyanshu    bca     33      32
5     Simran    mca     32      11
6      Anshu  btech     28      10