In [1]:
import pandas as pd

In [ ]:
# Null values find, fill

In [2]:
import numpy as np

In [22]:
df=pd.DataFrame({'Name':['Sourav','Priyanshu','Simran','Anshu',np.nan,'Anurag','Priyanka'],'class':['btech','bca','mca','btech','mcom','mba',np.nan],'Rollno':[34,np.nan,11,10,np.nan,67,89]})
df

        Name  class  Rollno
0     Sourav  btech    34.0
1  Priyanshu    bca     NaN
2     Simran    mca    11.0
3      Anshu  btech    10.0
4        NaN   mcom     NaN
5     Anurag    mba    67.0
6   Priyanka    NaN    89.0

In [23]:
df.isnull()

    Name  class  Rollno
0  False  False   False
1  False  False    True
2  False  False   False
3  False  False   False
4   True  False    True
5  False  False   False
6  False   True   False

In [24]:
df.isnull().sum()

Name      1
class     1
Rollno    2
dtype: int64

In [25]:
df.isna().sum()

Name      1
class     1
Rollno    2
dtype: int64

In [26]:
df.isnull().any()

Name      True
class     True
Rollno    True
dtype: bool

In [27]:
df.Name

0       Sourav
1    Priyanshu
2       Simran
3        Anshu
4          NaN
5       Anurag
6     Priyanka
Name: Name, dtype: object

In [28]:
df[df.Name.isnull()]

  Name class  Rollno
4  NaN  mcom     NaN

In [29]:
df[df.Rollno.isnull()]

        Name class  Rollno
1  Priyanshu   bca     NaN
4        NaN  mcom     NaN

In [30]:
df[df['class'].isnull()]

       Name class  Rollno
6  Priyanka   NaN    89.0

In [31]:
df.loc[1,'Rollno']=23
df.loc[4,'Rollno']=43

In [32]:
df

        Name  class  Rollno
0     Sourav  btech    34.0
1  Priyanshu    bca    23.0
2     Simran    mca    11.0
3      Anshu  btech    10.0
4        NaN   mcom    43.0
5     Anurag    mba    67.0
6   Priyanka    NaN    89.0

In [34]:
df['class'].mode()

0    btech
Name: class, dtype: object

In [37]:
df.loc[6,'class']=df['class'].mode()[0]

In [38]:
df

        Name  class  Rollno
0     Sourav  btech    34.0
1  Priyanshu  btech    23.0
2     Simran    mca    11.0
3      Anshu  btech    10.0
4        NaN   mcom    43.0
5     Anurag    mba    67.0
6   Priyanka  btech    89.0

In [39]:
df1=pd.DataFrame({'Name':['Sourav','Priyanshu','Simran','Anshu',np.nan,'Anurag','Priyanka'],'class':['btech','bca','mca','btech','mcom','mba',np.nan],'Rollno':[34,np.nan,11,10,np.nan,67,89]})
df1

        Name  class  Rollno
0     Sourav  btech    34.0
1  Priyanshu    bca     NaN
2     Simran    mca    11.0
3      Anshu  btech    10.0
4        NaN   mcom     NaN
5     Anurag    mba    67.0
6   Priyanka    NaN    89.0

In [40]:
df1.fillna(10)

        Name  class  Rollno
0     Sourav  btech    34.0
1  Priyanshu    bca    10.0
2     Simran    mca    11.0
3      Anshu  btech    10.0
4         10   mcom    10.0
5     Anurag    mba    67.0
6   Priyanka     10    89.0

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      object
 1   class   7 non-null      object
 2   Rollno  7 non-null      float64
dtypes: float64(1), object(2)
memory usage: 300.0+ bytes

In [41]:
df.describe()

          Rollno
count   7.000000
mean   39.571429
std    29.449715
min    10.000000
25%    17.000000
50%    34.000000
75%    55.000000
max    89.000000

In [43]:
# Percentile  

l=pd.DataFrame([12,17,14,19,20,21])
l

    0
0  12
1  17
2  14
3  19
4  20
5  21

In [44]:
l.describe()

               0
count   6.000000
mean   17.166667
std     3.544949
min    12.000000
25%    14.750000
50%    18.000000
75%    19.750000
max    21.000000

In [ ]:
# datasets - files read excel files, json, csv files